### PR TITLE
Dlm17 fixing clocks

### LINKED ISSUE #17: Fix clocks so the main MCU can run at the full 216 MHz
To make everything work, clock is at 96MHz in the current configuration

### LINKED ISSUE #20: Explore external oscillators
Right now the dev board uses an external oscillator from the USB. Actual hardware will not have that

### PR DESCRIPTION
**Pull request by caljay98**
Fixed clocks to run at 192MHz, the highest possible to keep CAN timings. No more relying on the ST link USB clock, which was always stupid

### CODE REVIEW

File: DLM_code/Src/dlm-manage_data_aquisition.c [hunk 1]
```diff
@@ -240,14 +241,16 @@ void store_new_data()
...
                 if (add_param_to_ram(param_node, bucket_node))
                 {
-                	// TODO error handling
-
-                	// for now, turn on the onboard LED
-                	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_SET);
+                	// TODO malloc error handling
 
+                	// for now, turn on the onboard LED (ld2, blue)
+                	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_SET);
```
Comment (hocally) [inline DLM_code/Src/dlm-manage_data_aquisition.c:247]: Is this for manual testing? Makes sense, there might be some other things to do once we hit a soft fault like that. Might be nice to explore the watchdog timers, if we have a malloc fail we could just hang out to let the watchdog reset us
